site_name: Consulta à Legislação de Maricá
docs_dir: legislatura

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant         # Navegação mais rápida
    - navigation.tracking        # Destaca seção atual
    - navigation.tabs            # Tabs no topo
    - navigation.tabs.sticky     # Tabs fixas ao rolar
    - navigation.expand          # Expande árvore de navegação
    - toc.follow                 # Sumário segue a rolagem
    - content.code.copy          # Botão "copiar código"
    - content.action.edit        # Botão "editar no GitHub"
    - content.action.view        # Botão "ver no GitHub"
    - search.suggest             # Sugestões automáticas
    - search.highlight           # Realce na busca
    - search.share               # Compartilhar termos buscados
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro

nav:
  - Início: index.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets

plugins:
  - search:
      lang: pt
      separator: '[\s\-\.]+'
